language: python
python:
  - "3.5"

before_install:
  - wget http://www.antlr.org/download/antlr-4.5.1-complete.jar
  - antlr4='java -jar antlr-4.5.1-complete.jar'

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "$antlr4 -visitor tinypy/parser/TinyPy.g4"
  - "pip install ."
  # Add subprocess support for coverage
  - SPACK=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
  - printf "\nimport coverage; coverage.process_startup()\n" >> "$SPACK/sitecustomize.py"

# command to run tests
script:
  - "coverage run setup.py test"
  - "coverage combine"
  - "coverage report"

after_success:
  coveralls