language: python
python:
  - "3.5"
  - "pypy"

#before_install:
#  - java install oraclejdk8
#  - cd /usr/local/lib
#  - export CLASSPATH=".:/usr/local/lib/antlr-4.5.1-complete.jar:$CLASSPATH"
#  - alias antlr4='java -jar /usr/local/lib/antlr-4.5.1-complete.jar'
#  - wget http://www.antlr.org/download/antlr-4.5.1-complete.jar

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "git clone https://github.com/maxmalysh/tiny-py-interpreter-auto-gen"
  - "cp tiny-py-interpreter-auto-gen/* ./parser"
  - "pip install ."
  -
# command to run tests
script: "python setup.py test"
